server:
  port: 8081
#for mysql or PostgreSQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Richa12345
    #url: jdbc:postgresql://localhost:5432/bms
    url: jdbc:mysql://localhost:3306/bms
  jpa:
    #generate-ddl: on //not used SB version 3 onwards
    hibernate:
      #dialect: org.hibernate.dialect.PostgreSQLDialect
      #dialect: org.hibernate.dialect.MySQL8Dialect //not used SB version 4 onwards
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG


